# Generated by Django 4.1 on 2022-08-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='division',
        ),
    ]
