# Generated by Django 4.1 on 2022-08-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ivision',
        ),
    ]
